In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('adult_dataset.csv')

In [3]:
df

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0.0,0.0,40.0,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0.0,0.0,50.0,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0.0,0.0,40.0,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688.0,0.0,40.0,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0.0,0.0,30.0,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9700,46,Private,173461,Some-college,10,Married-civ-spouse,Sales,Wife,White,Female,0.0,0.0,40.0,United-States,>50K
9701,48,Private,349986,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,99999.0,0.0,50.0,United-States,>50K
9702,24,Private,204244,9th,5,Never-married,Other-service,Not-in-family,White,Female,0.0,0.0,37.0,United-States,<=50K
9703,31,Private,36222,HS-grad,9,Separated,Handlers-cleaners,Not-in-family,White,Male,0.0,0.0,65.0,United-States,<=50K
9704,38,Self-emp-inc,320811,HS-grad,9,Married-civ-spous,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.describe()

,age,fnlwgt,educational-num,capital-gain,capital-loss,hours-per-week
count,9705.000000,9.705000e+03,9705.000000,9704.000000,9704.000000,9704.000000
mean,38.745595,1.884328e+05,10.078001,1132.703421,88.221043,40.506595
std,13.847549,1.051819e+05,2.566469,7981.949781,404.630715,12.407787
min,17.000000,1.376900e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.154870e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.779070e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.375230e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.490400e+06,16.000000,99999.000000,3770.000000,99.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9705 entries, 0 to 9704
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              9705 non-null   int64
 1   workclass        9705 non-null   object
 2   fnlwgt           9705 non-null   int64
 3   education        9705 non-null   object
 4   educational-num  9705 non-null   int64
 5   marital-status   9705 non-null   object
 6   occupation       9704 non-null   object
 7   relationship     9704 non-null   object
 8   race             9704 non-null   object
 9   gender           9704 non-null   object
 10  capital-gain     9704 non-null   float64
 11  capital-loss     9704 non-null   float64
 12  hours-per-week   9704 non-null   float64
 13  native-country   9704 non-null   object
 14  income           9704 non-null   object
dtypes: float64(3), int64(3), object(9)
memory usage: 1.1+ MB

In [10]:
subset1 = df[['age', 'workclass', 'education', 'income']]

print(subset1)

      age     workclass     education income
0      25       Private          11th  <=50K
1      38       Private       HS-grad  <=50K
2      28     Local-gov    Assoc-acdm   >50K
3      44       Private  Some-college   >50K
4      18             ?  Some-college  <=50K
...   ...           ...           ...    ...
9700   46       Private  Some-college   >50K
9701   48       Private   Prof-school   >50K
9702   24       Private           9th  <=50K
9703   31       Private       HS-grad  <=50K
9704   38  Self-emp-inc       HS-grad    NaN

[9705 rows x 4 columns]

In [11]:
# Subset 2: gender, race, Category, capital-gain
subset2 = df[['age', 'occupation', 'gender', 'capital-gain']]

print(subset2)

      age         occupation  gender  capital-gain
0      25  Machine-op-inspct    Male           0.0
1      38    Farming-fishing    Male           0.0
2      28    Protective-serv    Male           0.0
3      44  Machine-op-inspct    Male        7688.0
4      18                  ?  Female           0.0
...   ...                ...     ...           ...
9700   46              Sales  Female           0.0
9701   48     Prof-specialty    Male       99999.0
9702   24      Other-service  Female           0.0
9703   31  Handlers-cleaners    Male           0.0
9704   38                NaN     NaN           NaN

[9705 rows x 4 columns]

In [12]:
# Merge Subset1 and Subset2 based on 'age'
merged_data = pd.merge(subset1, subset2, on='age')
print("\nMerged Subset1 and Subset2 (on 'age'):")
print(merged_data)

Merged Subset1 and Subset2 (on 'age'):
         age     workclass education income         occupation  gender  \
0         25       Private      11th  <=50K  Machine-op-inspct    Male
1         25       Private      11th  <=50K     Prof-specialty    Male
2         25       Private      11th  <=50K     Prof-specialty    Male
3         25       Private      11th  <=50K    Exec-managerial  Female
4         25       Private      11th  <=50K       Adm-clerical  Female
...      ...           ...       ...    ...                ...     ...
1995444   38  Self-emp-inc   HS-grad    NaN       Craft-repair    Male
1995445   38  Self-emp-inc   HS-grad    NaN              Sales  Female
1995446   38  Self-emp-inc   HS-grad    NaN    Exec-managerial    Male
1995447   38  Self-emp-inc   HS-grad    NaN    Exec-managerial    Male
1995448   38  Self-emp-inc   HS-grad    NaN                NaN     NaN

         capital-gain
0                 0.0
1                 0.0
2                 0.0
3                 0.0
4                 0.0
...               ...
1995444           0.0
1995445           0.0
1995446           0.0
1995447           0.0
1995448           NaN

[1995449 rows x 7 columns]

In [13]:
# Merge Subset1 and Subset2 based on different columns
merged_different_cols = pd.merge(subset1, subset2, left_on='workclass', right_on='occupation')

print("\nMerged Subset1 and Subset2 (left_on='workclass', right_on='occupation'):")
print(merged_different_cols)

Merged Subset1 and Subset2 (left_on='workclass', right_on='occupation'):
        age_x workclass     education income  age_y occupation  gender  \
0          18         ?  Some-college  <=50K     18          ?  Female
1          18         ?  Some-college  <=50K     29          ?    Male
2          18         ?  Some-college  <=50K     58          ?    Male
3          18         ?  Some-college  <=50K     72          ?  Female
4          18         ?  Some-college  <=50K     65          ?    Male
...       ...       ...           ...    ...    ...        ...     ...
346327     18         ?          12th  <=50K     42          ?  Female
346328     18         ?          12th  <=50K     23          ?  Female
346329     18         ?          12th  <=50K     17          ?    Male
346330     18         ?          12th  <=50K     58          ?    Male
346331     18         ?          12th  <=50K     18          ?    Male

        capital-gain
0                0.0
1                0.0
2                0.0
3                0.0
4                0.0
...              ...
346327           0.0
346328           0.0
346329           0.0
346330           0.0
346331           0.0

[346332 rows x 8 columns]

In [14]:
# Sorting merged_data in descending order wrt 'capital-gain'
merged_data.sort_values(by=['capital-gain'],ascending=False)

,age,workclass,education,income,occupation,gender,capital-gain
1851021,44,Private,HS-grad,>50K,Prof-specialty,Male,99999.0
522349,48,Private,Bachelors,>50K,Prof-specialty,Male,99999.0
1851015,44,Private,HS-grad,>50K,Prof-specialty,Male,99999.0
522351,48,Private,Bachelors,>50K,Craft-repair,Male,99999.0
1850994,44,Private,HS-grad,>50K,Craft-repair,Male,99999.0
...,...,...,...,...,...,...,...
1952027,38,Private,9th,>50K,NaN,NaN,NaN
1957069,38,Private,Some-college,<=50K,NaN,NaN,NaN
1979282,38,Private,Masters,>50K,NaN,NaN,NaN
1993532,38,Self-emp-inc,HS-grad,<=50K,NaN,NaN,NaN
1995448,38,Self-emp-inc,HS-grad,NaN,NaN,NaN,NaN

In [15]:
# Method 1
merged_data.transpose()

,0,1,2,3,4,5,6,7,8,9,...,1995439,1995440,1995441,1995442,1995443,1995444,1995445,1995446,1995447,1995448
age,25,25,25,25,25,25,25,25,25,25,...,38,38,38,38,38,38,38,38,38,38
workclass,Private,Private,Private,Private,Private,Private,Private,Private,Private,Private,...,Self-emp-inc,Self-emp-inc,Self-emp-inc,Self-emp-inc,Self-emp-inc,Self-emp-inc,Self-emp-inc,Self-emp-inc,Self-emp-inc,Self-emp-inc
education,11th,11th,11th,11th,11th,11th,11th,11th,11th,11th,...,HS-grad,HS-grad,HS-grad,HS-grad,HS-grad,HS-grad,HS-grad,HS-grad,HS-grad,HS-grad
income,<=50K,<=50K,<=50K,<=50K,<=50K,<=50K,<=50K,<=50K,<=50K,<=50K,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
occupation,Machine-op-inspct,Prof-specialty,Prof-specialty,Exec-managerial,Adm-clerical,Other-service,Machine-op-inspct,?,Other-service,Exec-managerial,...,Exec-managerial,Exec-managerial,Prof-specialty,Adm-clerical,Transport-moving,Craft-repair,Sales,Exec-managerial,Exec-managerial,NaN
gender,Male,Male,Male,Female,Female,Female,Female,Female,Female,Male,...,Male,Female,Male,Female,Male,Male,Female,Male,Male,NaN
capital-gain,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1055.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN

In [16]:
# Method 2
merged_data.T

,0,1,2,3,4,5,6,7,8,9,...,1995439,1995440,1995441,1995442,1995443,1995444,1995445,1995446,1995447,1995448
age,25,25,25,25,25,25,25,25,25,25,...,38,38,38,38,38,38,38,38,38,38
workclass,Private,Private,Private,Private,Private,Private,Private,Private,Private,Private,...,Self-emp-inc,Self-emp-inc,Self-emp-inc,Self-emp-inc,Self-emp-inc,Self-emp-inc,Self-emp-inc,Self-emp-inc,Self-emp-inc,Self-emp-inc
education,11th,11th,11th,11th,11th,11th,11th,11th,11th,11th,...,HS-grad,HS-grad,HS-grad,HS-grad,HS-grad,HS-grad,HS-grad,HS-grad,HS-grad,HS-grad
income,<=50K,<=50K,<=50K,<=50K,<=50K,<=50K,<=50K,<=50K,<=50K,<=50K,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
occupation,Machine-op-inspct,Prof-specialty,Prof-specialty,Exec-managerial,Adm-clerical,Other-service,Machine-op-inspct,?,Other-service,Exec-managerial,...,Exec-managerial,Exec-managerial,Prof-specialty,Adm-clerical,Transport-moving,Craft-repair,Sales,Exec-managerial,Exec-managerial,NaN
gender,Male,Male,Male,Female,Female,Female,Female,Female,Female,Male,...,Male,Female,Male,Female,Male,Male,Female,Male,Male,NaN
capital-gain,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1055.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN

In [17]:
df

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0.0,0.0,40.0,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0.0,0.0,50.0,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0.0,0.0,40.0,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688.0,0.0,40.0,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0.0,0.0,30.0,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9700,46,Private,173461,Some-college,10,Married-civ-spouse,Sales,Wife,White,Female,0.0,0.0,40.0,United-States,>50K
9701,48,Private,349986,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,99999.0,0.0,50.0,United-States,>50K
9702,24,Private,204244,9th,5,Never-married,Other-service,Not-in-family,White,Female,0.0,0.0,37.0,United-States,<=50K
9703,31,Private,36222,HS-grad,9,Separated,Handlers-cleaners,Not-in-family,White,Male,0.0,0.0,65.0,United-States,<=50K
9704,38,Self-emp-inc,320811,HS-grad,9,Married-civ-spous,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
# Reshape
pd.melt(df, id_vars =['education'], value_vars =['capital-gain'])

         education      variable    value
0             11th  capital-gain      0.0
1          HS-grad  capital-gain      0.0
2       Assoc-acdm  capital-gain      0.0
3     Some-college  capital-gain   7688.0
4     Some-college  capital-gain      0.0
...            ...           ...      ...
9700  Some-college  capital-gain      0.0
9701   Prof-school  capital-gain  99999.0
9702           9th  capital-gain      0.0
9703       HS-grad  capital-gain      0.0
9704       HS-grad  capital-gain      NaN

[9705 rows x 3 columns]